//Test
// export const ONE_MORE = 'ONE_MORE';
// export const ONE_LESS = 'ONE_LESS';
// is Show introduction in first time
export const IS_SHOW = 'IS_SHOW';
export const YES = 'YES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCHING_MOVIES = 'SEARCHING_MOVIES';
export const LOADING_MOVIE_DETAIL = 'LOADING_MOVIE_DETAIL';

export const SEARCH_MOVIES_MORE = 'SEARCH_MOVIES_MORE';
export const CLEAR_SEARCH_MOVIES = 'CLEAR_SEARCH_MOVIES';
export const MOVIES_POPULAR = 'POPULAR_POPULAR';
export const MOVIE_DETAIL = 'MOVIE_DETAIL';
export const MOVIE_DETAIL_ERROR = 'MOVIE_DETAIL_ERROR';
export const DETAIL_GUEST_MOVIES = 'DETAIL_GUEST_MOVIES';
export const CLEAR_DETAIL_MOVIE = 'CLEAR_DETAIL_MOVIE';
export const IS_LOADING_DETAIL_GUEST_MOVIES = 'IS_LOADING_DETAIL_GUEST_MOVIES';

//MOVIE BY CATEGORIES
export const MOVIES_ACTION = 'MOVIES_ACTION';
export const MOVIES_ADVENTURE = 'MOVIES_ADVENTURE';
export const MOVIES_ANIMATION = 'MOVIES_ANIMATION';
export const MOVIES_COMEDY = 'MOVIES_COMEDY';
export const MOVIES_CRIME = 'MOVIES_CRIME';
export const MOVIES_DOCUMENTARY = 'MOVIES_DOCUMENTARY';
export const MOVIES_DRAMA = 'MOVIES_DRAMA';
export const MOVIES_FAMILY = 'MOVIES_FAMILY';
export const MOVIES_FANTASY = 'MOVIES_FANTASY';
export const MOVIES_HISTORY = 'MOVIES_HISTORY';
export const MOVIES_HORROR = 'MOVIES_HORROR';
export const MOVIES_MUSIC = 'MOVIES_MUSIC';
export const MOVIES_MYSTERY = 'MOVIES_MYSTERY';
export const MOVIES_ROMANCE = 'MOVIES_ROMANCE';
export const MOVIES_SCIENCE_FICTION = 'MOVIES_SCIENCE_FICTION';
export const MOVIES_TV_MOVIE = 'MOVIES_TV_MOVIE';
export const MOVIES_THRILLER = 'MOVIES_THRILLER';
export const MOVIES_WAR = 'MOVIES_WAR';
export const MOVIES_WESTERN = 'MOVIES_WESTERN';

// MOVIE_LOADED
export const MOVIES_ACTION_LOADED = 'MOVIES_ACTION_LOADED';
export const MOVIES_ADVENTURE_LOADED = 'MOVIES_ADVENTURE_LOADED';
export const MOVIES_ANIMATION_LOADED = 'MOVIES_ANIMATION_LOADED';
export const MOVIES_COMEDY_LOADED = 'MOVIES_COMEDY_LOADED';
export const MOVIES_CRIME_LOADED = 'MOVIES_CRIME_LOADED';
export const MOVIES_DOCUMENTARY_LOADED = 'MOVIES_DOCUMENTARY_LOADED';
export const MOVIES_DRAMA_LOADED = 'MOVIES_DRAMA_LOADED';
export const MOVIES_FAMILY_LOADED = 'MOVIES_FAMILY_LOADED';
export const MOVIES_FANTASY_LOADED = 'MOVIES_FANTASY_LOADED';
export const MOVIES_HISTORY_LOADED = 'MOVIES_HISTORY_LOADED';
export const MOVIES_HORROR_LOADED = 'MOVIES_HORROR_LOADED';
export const MOVIES_MUSIC_LOADED = 'MOVIES_MUSIC_LOADED';
export const MOVIES_MYSTERY_LOADED = 'MOVIES_MYSTERY_LOADED';
export const MOVIES_ROMANCE_LOADED = 'MOVIES_ROMANCE_LOADED';
export const MOVIES_SCIENCE_FICTION_LOADED = 'MOVIES_SCIENCE_FICTION_LOADED';
export const MOVIES_TV_MOVIE_LOADED = 'MOVIES_TV_MOVIE_LOADED';
export const MOVIES_THRILLER_LOADED = 'MOVIES_THRILLER_LOADED';
export const MOVIES_WAR_LOADED = 'MOVIES_WAR_LOADED';
export const MOVIES_WESTERN_LOADED = 'MOVIES_WESTERN_LOADED';
